on: [push, pull_request]
name: SQLX_Integration_tests
jobs:
  tests:
    strategy:
      matrix:
        go-version: [ 1.18.x ]
        os: [ ubuntu-latest ] # [ macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Create Postgres container
        run: sudo docker network create postgres-test && sudo docker run -d -p 5433:5432 -e "POSTGRES_USER=test" -e "POSTGRES_PASSWORD=test" --network postgres-test postgres:13

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        working-directory: db
        run: make tests
